### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by linhx** [linhx/ckeditor5-emoji#1]
- [x] copy paste
- [x] drag
- [x] sometimes emoji auto turn into text
- [x] fix warning missing focus method
- [x] delete within 1 pressed
